package transactions

type TxType string

const (
	AccountSetTx           TxType = "AccountSet"
	AccountDeleteTx               = "AccountDelete"
	AMMBidTx                      = "AMMBid"
	AMMCreateTx                   = "AMMCreate"
	AMMDepositTx                  = "AMMDeposit"
	AMMVoteTx                     = "AMMVote"
	AMMWithdrawTx                 = "AMMWithdraw"
	CheckCancelTx                 = "CheckCancel"
	CheckCashTx                   = "CheckCash"
	CheckCreateTx                 = "CheckCreate"
	DepositPreauthTx              = "DepositPreauth"
	EscrowCancelTx                = "EscrowCancel"
	EscrowCreateTx                = "EscrowCreate"
	EscrowFinishTx                = "EscrowFinish"
	NFTokenAcceptOfferTx          = "NFTokenAcceptOffer"
	NFTokenBurnTx                 = "NFTokenBurn"
	NFTokenCancelOfferTx          = "NFTokenCancelOffer"
	NFTokenCreateOfferTx          = "NFTokenCreateOffer"
	NFTokenMintTx                 = "NFTokenMint"
	OfferCreateTx                 = "OfferCreate"
	OfferCancelTx                 = "OfferCancel"
	PaymentTx                     = "Payment"
	PaymentChannelClaimTx         = "PaymentChannelClaim"
	PaymentChannelCreateTx        = "PaymentChannelCreate"
	PaymentChannelFundTx          = "PaymentChannelFund"
	SetRegularKeyTx               = "SetRegularKey"
	SignerListSetTx               = "SignerListSet"
	TrustSetTx                    = "TrustSet"
	TicketCreateTx                = "TicketCreate"
)
